`ifdef SPLIT_1024_CONFIG
  `define INPUT_DATA_BUS_WIDTH 1024
  `define NO_OF_CYCLES_PER_FLIT 2
  `define SPLIT_DATA_WIDTH 512
  `define NO_OF_CYCLES_PER_SPLIT_DATA 4

`elsif NO_SPLIT_1024_CONFIG
  `define INPUT_DATA_BUS_WIDTH 1024
  `define NO_OF_CYCLES_PER_FLIT 2

`endif
